services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
#    volumes:
#      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
#    volumes:
#      - ./frontend:/app
    stdin_open: true
    tty: true

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: